# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d3eb65b73871ecce69768d48ed1af750420831a796be331346a2d1da6cb277d83b65b1d821e570ecca8b6e9365258bbbc4e08872d16dfa5e5a1165dad10c7ba

test:
  secret_key_base: f8520fdc479427f9304ae559519a69ccf36a6b643db40be78a98d8a80dca284f609413d90adc65004c6b1620350865086d58739303eceb5e3f909dd8dbab1112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
